FROM tomcat:9.0-jre8


ARG warFile


COPY $warFile $CATALINA_HOME/webapps/roar.war


# Add a tomcat user
RUN groupadd -r tomcat && useradd -g tomcat -d ${CATALINA_HOME} -s /bin/bash tomcat

RUN chown -R tomcat:tomcat $CATALINA_HOME

USER tomcat


CMD ["catalina.sh", "run"]

